#!/bin/bash
#PBS -l nodes=1:ppn=16:dc2,walltime=0:45:00
#PBS -N app-generatetractmasks
#PBS -V

if [ $ENV == "IUHPC" ]; then
	cd $PBS_O_WORKDIR
	module load matlab
fi

export MATLABPATH=$MATLABPATH:$SERVICE_DIR
matlab -nodisplay -nosplash -r main

#if [ -s masks/Right_Uncinate_Vol.nii.gz ];
count=$(ls masks/*Vol.nii.gz | wc -l)
if [ $count -eq 20 ] 
then 
  echo 0 > finished
else
  echo "files missing"
  echo 1 > finished
  exit 1
fi
